spring:
    application:
        name: config-server
    profiles:
        active: default
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/LeonelFabianBahamonSoto/ms-companies.git
                    default-label: main
                    clone-on-start: true

server:
    port: 8888

eureka:
    instance:
        instance-id: "${spring.application.name}:${random.value}"
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/