spring:
  application:
    name: companies-crud
  datasource:
    url: jdbc:postgresql://localhost:5432/companies
    username: fabian
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari.connection-timeout: 20000
    hikari.maximum-pool-size: 5

server:
  port: 8081
  servlet:
    context-path: /companies

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/